# Generated by Django 5.0.8 on 2024-09-15 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="name",
        ),
    ]
