# Generated by Django 5.0.8 on 2024-09-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_remove_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.ImageField(default="default.png", upload_to="product_images/"),
        ),
    ]
