# Generated by Django 5.0.8 on 2024-09-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_product_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.ImageField(
                default="product_images/default.png", upload_to="product_images/"
            ),
        ),
    ]
